steps:
  # Build the backend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/audit-copilot-backend:$COMMIT_SHA', './backend']
  
  # Push the backend image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/audit-copilot-backend:$COMMIT_SHA']
  
  # Build the frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/audit-copilot-ui:$COMMIT_SHA', './compliance_review_ui']
  
  # Push the frontend image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/audit-copilot-ui:$COMMIT_SHA']
  
  # Access DB password from Secret Manager
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        DB_PASSWORD=$$(gcloud secrets versions access latest --secret=db-password)
        echo "DB_HOST=127.0.0.1,DB_PORT=5432,DB_USER=postgres,DB_PASSWORD=$$DB_PASSWORD,DB_NAME=auditcopilot" > db_env.txt
  
  # Deploy backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'audit-copilot-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/audit-copilot-backend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--add-cloudsql-instances'
      - '${_DB_CONNECTION_NAME}'
      - '--set-env-vars-file'
      - 'db_env.txt'
  
  # Get the backend URL
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        BACKEND_URL=$(gcloud run services describe audit-copilot-backend --format='value(status.url)')
        echo "Backend URL: $BACKEND_URL"
        echo "VITE_API_BASE_URL=$BACKEND_URL" > api_url.env
  
  # Deploy frontend to Cloud Run with the API URL
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'audit-copilot-ui'
      - '--image'
      - 'gcr.io/$PROJECT_ID/audit-copilot-ui:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars-file'
      - 'api_url.env'

images:
  - 'gcr.io/$PROJECT_ID/audit-copilot-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/audit-copilot-ui:$COMMIT_SHA'

substitutions:
  _DB_CONNECTION_NAME: 'YOUR-PROJECT-ID:us-central1:auditcopilot-db'  # Update this with your actual connection name

options:
  logging: CLOUD_LOGGING_ONLY
