services:
  web:
    build: .
    image: auditcopilot.azurecr.io/web:v3_turing_demo
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - OUTPUT_DIR=/app/outputs
    volumes:
      - ./jnj_outputs:/app/outputs
      - ./chromadb:/app/chromadb
      - ./chromadb_new:/app/chromadb_new

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  # frontend:
  #   build: ./react_app
  #   image: auditcopilot.azurecr.io/frontend:v2_turing_demo
  #   command: ["npm", "run", "start"]
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - web
  #   environment:
  #     - REACT_APP_API_URL=http://20.41.252.65:8000
  #   volumes:
  #     - ./react_app:/app
  #     - /app/node_modules
