FROM node:18

WORKDIR /app

COPY package.json package-lock.json ./

# Clear old lock + install clean
RUN rm -rf node_modules package-lock.json && npm install

COPY . .

EXPOSE 5173

ENV NODE_ENV=development
ENV CHOKIDAR_USEPOLLING=true

CMD ["npm", "run", "dev"]
